<?xml version="1.0" ?>
<!-- Configuration of the Ant build system to generate a Jar file --> 
<project name="NanoTool" default="CreateJar">
  <target name="CreateJar" description="Create Jar file">
        <jar jarfile="../NanoTool.jar" basedir="." includes="*.class" />
  </target>
</project>
